/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new PlayerText:BatteryIndicatorMinimize[MAX_PLAYERS];
new PlayerText:BatteryIndicatorMaximize[MAX_PLAYERS];

//Textdraws

//Player Textdraws
BatteryIndicatorMinimize[playerid] = CreatePlayerTextDraw(playerid, 430.000000, 433.000000, "100.00%");
PlayerTextDrawFont(playerid, BatteryIndicatorMinimize[playerid], 1);
PlayerTextDrawLetterSize(playerid, BatteryIndicatorMinimize[playerid], 0.133330, 0.599995);
PlayerTextDrawTextSize(playerid, BatteryIndicatorMinimize[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, BatteryIndicatorMinimize[playerid], 0);
PlayerTextDrawSetShadow(playerid, BatteryIndicatorMinimize[playerid], 0);
PlayerTextDrawAlignment(playerid, BatteryIndicatorMinimize[playerid], 1);
PlayerTextDrawColor(playerid, BatteryIndicatorMinimize[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, BatteryIndicatorMinimize[playerid], 255);
PlayerTextDrawBoxColor(playerid, BatteryIndicatorMinimize[playerid], 50);
PlayerTextDrawUseBox(playerid, BatteryIndicatorMinimize[playerid], 0);
PlayerTextDrawSetProportional(playerid, BatteryIndicatorMinimize[playerid], 1);
PlayerTextDrawSetSelectable(playerid, BatteryIndicatorMinimize[playerid], 0);

BatteryIndicatorMaximize[playerid] = CreatePlayerTextDraw(playerid, 429.000000, 287.000000, "100.00%");
PlayerTextDrawFont(playerid, BatteryIndicatorMaximize[playerid], 1);
PlayerTextDrawLetterSize(playerid, BatteryIndicatorMaximize[playerid], 0.133330, 0.599995);
PlayerTextDrawTextSize(playerid, BatteryIndicatorMaximize[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, BatteryIndicatorMaximize[playerid], 0);
PlayerTextDrawSetShadow(playerid, BatteryIndicatorMaximize[playerid], 0);
PlayerTextDrawAlignment(playerid, BatteryIndicatorMaximize[playerid], 1);
PlayerTextDrawColor(playerid, BatteryIndicatorMaximize[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, BatteryIndicatorMaximize[playerid], 255);
PlayerTextDrawBoxColor(playerid, BatteryIndicatorMaximize[playerid], 50);
PlayerTextDrawUseBox(playerid, BatteryIndicatorMaximize[playerid], 0);
PlayerTextDrawSetProportional(playerid, BatteryIndicatorMaximize[playerid], 1);
PlayerTextDrawSetSelectable(playerid, BatteryIndicatorMaximize[playerid], 0);


/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
