/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

#include <a_samp>
#include <progress2>
//Requires "progress2" include by Southclaws
//Download: https://github.com/Southclaws/progress2/releases

new PlayerText:FishingPowerText[MAX_PLAYERS];
new PlayerBar:FishingProgressBar[MAX_PLAYERS];

public OnFilterScriptInit()
{
	return 1;
}

public OnFilterScriptExit()
{
	return 1;
}

public OnPlayerConnect(playerid)
{
	FishingPowerText[playerid] = CreatePlayerTextDraw(playerid, 268.000000, 371.000000, "Fishing Power");
	PlayerTextDrawFont(playerid, FishingPowerText[playerid], 1);
	PlayerTextDrawLetterSize(playerid, FishingPowerText[playerid], 0.341666, 1.299999);
	PlayerTextDrawTextSize(playerid, FishingPowerText[playerid], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, FishingPowerText[playerid], 1);
	PlayerTextDrawSetShadow(playerid, FishingPowerText[playerid], 0);
	PlayerTextDrawAlignment(playerid, FishingPowerText[playerid], 1);
	PlayerTextDrawColor(playerid, FishingPowerText[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, FishingPowerText[playerid], 255);
	PlayerTextDrawBoxColor(playerid, FishingPowerText[playerid], 50);
	PlayerTextDrawUseBox(playerid, FishingPowerText[playerid], 0);
	PlayerTextDrawSetProportional(playerid, FishingPowerText[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, FishingPowerText[playerid], 0);

	FishingProgressBar[playerid] = CreatePlayerProgressBar(playerid, 270.000000, 386.000000, 129.500000, 9.500000, -1, 20.000000, 0);
	SetPlayerProgressBarValue(playerid, FishingProgressBar[playerid], 10.000000);

	return 1;
}

public OnPlayerDisconnect(playerid, reason)
{
	PlayerTextDrawDestroy(playerid, FishingPowerText[playerid]);
	DestroyPlayerProgressBar(playerid, FishingProgressBar[playerid]);
	return 1;
}

public OnPlayerCommandText(playerid, cmdtext[])
{
	if(!strcmp(cmdtext, "/tdtest", true))
	{
		PlayerTextDrawShow(playerid, FishingPowerText[playerid]);
		ShowPlayerProgressBar(playerid, FishingProgressBar[playerid]);
		return 1;
	}
	return 0;
}
