/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

#include <a_samp>

new PlayerText:PlayerTD[MAX_PLAYERS][1];
new PlayerText:BOX1[MAX_PLAYERS];
new PlayerText:BOX2[MAX_PLAYERS];
new PlayerText:ScreenBG[MAX_PLAYERS];
new PlayerText:BOX3[MAX_PLAYERS];
new PlayerText:MidButton[MAX_PLAYERS];
new PlayerText:IncomingNumber[MAX_PLAYERS];
new PlayerText:IncomingCall[MAX_PLAYERS];
new PlayerText:AcceptCall[MAX_PLAYERS];
new PlayerText:DeniedCall[MAX_PLAYERS];
new PlayerText:BatteryTD[MAX_PLAYERS];
new PlayerText:PhoneNumber[MAX_PLAYERS];
new PlayerText:Battery[MAX_PLAYERS];

public OnFilterScriptInit()
{
	return 1;
}

public OnFilterScriptExit()
{
	return 1;
}

public OnPlayerConnect(playerid)
{
	BOX1[playerid] = CreatePlayerTextDraw(playerid, 184.000000, 285.000000, "_");
	PlayerTextDrawFont(playerid, BOX1[playerid], 0);
	PlayerTextDrawLetterSize(playerid, BOX1[playerid], 0.600000, 17.600000);
	PlayerTextDrawTextSize(playerid, BOX1[playerid], 298.500000, 75.000000);
	PlayerTextDrawSetOutline(playerid, BOX1[playerid], 0);
	PlayerTextDrawSetShadow(playerid, BOX1[playerid], 0);
	PlayerTextDrawAlignment(playerid, BOX1[playerid], 2);
	PlayerTextDrawColor(playerid, BOX1[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, BOX1[playerid], 255);
	PlayerTextDrawBoxColor(playerid, BOX1[playerid], 255);
	PlayerTextDrawUseBox(playerid, BOX1[playerid], 1);
	PlayerTextDrawSetProportional(playerid, BOX1[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, BOX1[playerid], 0);

	BOX2[playerid] = CreatePlayerTextDraw(playerid, 184.000000, 289.000000, "_");
	PlayerTextDrawFont(playerid, BOX2[playerid], 1);
	PlayerTextDrawLetterSize(playerid, BOX2[playerid], 0.600000, 16.700016);
	PlayerTextDrawTextSize(playerid, BOX2[playerid], 298.500000, 68.000000);
	PlayerTextDrawSetOutline(playerid, BOX2[playerid], 1);
	PlayerTextDrawSetShadow(playerid, BOX2[playerid], 0);
	PlayerTextDrawAlignment(playerid, BOX2[playerid], 2);
	PlayerTextDrawColor(playerid, BOX2[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, BOX2[playerid], 255);
	PlayerTextDrawBoxColor(playerid, BOX2[playerid], -1);
	PlayerTextDrawUseBox(playerid, BOX2[playerid], 1);
	PlayerTextDrawSetProportional(playerid, BOX2[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, BOX2[playerid], 0);

	ScreenBG[playerid] = CreatePlayerTextDraw(playerid, 148.000000, 287.000000, "ld_dual:backgnd");
	PlayerTextDrawFont(playerid, ScreenBG[playerid], 4);
	PlayerTextDrawLetterSize(playerid, ScreenBG[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, ScreenBG[playerid], 72.000000, 154.000000);
	PlayerTextDrawSetOutline(playerid, ScreenBG[playerid], 1);
	PlayerTextDrawSetShadow(playerid, ScreenBG[playerid], 0);
	PlayerTextDrawAlignment(playerid, ScreenBG[playerid], 1);
	PlayerTextDrawColor(playerid, ScreenBG[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, ScreenBG[playerid], 255);
	PlayerTextDrawBoxColor(playerid, ScreenBG[playerid], 50);
	PlayerTextDrawUseBox(playerid, ScreenBG[playerid], 1);
	PlayerTextDrawSetProportional(playerid, ScreenBG[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, ScreenBG[playerid], 0);

	BOX3[playerid] = CreatePlayerTextDraw(playerid, 184.000000, 428.000000, "_");
	PlayerTextDrawFont(playerid, BOX3[playerid], 1);
	PlayerTextDrawLetterSize(playerid, BOX3[playerid], 0.600000, 1.499994);
	PlayerTextDrawTextSize(playerid, BOX3[playerid], 298.500000, 75.000000);
	PlayerTextDrawSetOutline(playerid, BOX3[playerid], 1);
	PlayerTextDrawSetShadow(playerid, BOX3[playerid], 0);
	PlayerTextDrawAlignment(playerid, BOX3[playerid], 2);
	PlayerTextDrawColor(playerid, BOX3[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, BOX3[playerid], 255);
	PlayerTextDrawBoxColor(playerid, BOX3[playerid], 255);
	PlayerTextDrawUseBox(playerid, BOX3[playerid], 1);
	PlayerTextDrawSetProportional(playerid, BOX3[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, BOX3[playerid], 0);

	MidButton[playerid] = CreatePlayerTextDraw(playerid, 176.000000, 426.000000, "ld_beat:cring");
	PlayerTextDrawFont(playerid, MidButton[playerid], 4);
	PlayerTextDrawLetterSize(playerid, MidButton[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, MidButton[playerid], 17.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, MidButton[playerid], 1);
	PlayerTextDrawSetShadow(playerid, MidButton[playerid], 0);
	PlayerTextDrawAlignment(playerid, MidButton[playerid], 1);
	PlayerTextDrawColor(playerid, MidButton[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, MidButton[playerid], 255);
	PlayerTextDrawBoxColor(playerid, MidButton[playerid], 50);
	PlayerTextDrawUseBox(playerid, MidButton[playerid], 1);
	PlayerTextDrawSetProportional(playerid, MidButton[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, MidButton[playerid], 1);

	IncomingNumber[playerid] = CreatePlayerTextDraw(playerid, 184.000000, 334.000000, "58192");
	PlayerTextDrawFont(playerid, IncomingNumber[playerid], 1);
	PlayerTextDrawLetterSize(playerid, IncomingNumber[playerid], 0.354166, 1.550000);
	PlayerTextDrawTextSize(playerid, IncomingNumber[playerid], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, IncomingNumber[playerid], 1);
	PlayerTextDrawSetShadow(playerid, IncomingNumber[playerid], 0);
	PlayerTextDrawAlignment(playerid, IncomingNumber[playerid], 2);
	PlayerTextDrawColor(playerid, IncomingNumber[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, IncomingNumber[playerid], 255);
	PlayerTextDrawBoxColor(playerid, IncomingNumber[playerid], 50);
	PlayerTextDrawUseBox(playerid, IncomingNumber[playerid], 0);
	PlayerTextDrawSetProportional(playerid, IncomingNumber[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, IncomingNumber[playerid], 0);

	IncomingCall[playerid] = CreatePlayerTextDraw(playerid, 155.000000, 363.000000, "Incoming Call");
	PlayerTextDrawFont(playerid, IncomingCall[playerid], 1);
	PlayerTextDrawLetterSize(playerid, IncomingCall[playerid], 0.258333, 1.450000);
	PlayerTextDrawTextSize(playerid, IncomingCall[playerid], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, IncomingCall[playerid], 1);
	PlayerTextDrawSetShadow(playerid, IncomingCall[playerid], 0);
	PlayerTextDrawAlignment(playerid, IncomingCall[playerid], 1);
	PlayerTextDrawColor(playerid, IncomingCall[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, IncomingCall[playerid], 255);
	PlayerTextDrawBoxColor(playerid, IncomingCall[playerid], 50);
	PlayerTextDrawUseBox(playerid, IncomingCall[playerid], 0);
	PlayerTextDrawSetProportional(playerid, IncomingCall[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, IncomingCall[playerid], 0);

	AcceptCall[playerid] = CreatePlayerTextDraw(playerid, 148.000000, 426.000000, "HUD:radar_light");
	PlayerTextDrawFont(playerid, AcceptCall[playerid], 4);
	PlayerTextDrawLetterSize(playerid, AcceptCall[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, AcceptCall[playerid], 16.500000, 18.000000);
	PlayerTextDrawSetOutline(playerid, AcceptCall[playerid], 1);
	PlayerTextDrawSetShadow(playerid, AcceptCall[playerid], 0);
	PlayerTextDrawAlignment(playerid, AcceptCall[playerid], 1);
	PlayerTextDrawColor(playerid, AcceptCall[playerid], 16711935);
	PlayerTextDrawBackgroundColor(playerid, AcceptCall[playerid], 255);
	PlayerTextDrawBoxColor(playerid, AcceptCall[playerid], 50);
	PlayerTextDrawUseBox(playerid, AcceptCall[playerid], 1);
	PlayerTextDrawSetProportional(playerid, AcceptCall[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, AcceptCall[playerid], 1);

	DeniedCall[playerid] = CreatePlayerTextDraw(playerid, 204.000000, 426.000000, "HUD:radar_light");
	PlayerTextDrawFont(playerid, DeniedCall[playerid], 4);
	PlayerTextDrawLetterSize(playerid, DeniedCall[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, DeniedCall[playerid], 16.500000, 18.000000);
	PlayerTextDrawSetOutline(playerid, DeniedCall[playerid], 1);
	PlayerTextDrawSetShadow(playerid, DeniedCall[playerid], 0);
	PlayerTextDrawAlignment(playerid, DeniedCall[playerid], 1);
	PlayerTextDrawColor(playerid, DeniedCall[playerid], -16776961);
	PlayerTextDrawBackgroundColor(playerid, DeniedCall[playerid], 255);
	PlayerTextDrawBoxColor(playerid, DeniedCall[playerid], 50);
	PlayerTextDrawUseBox(playerid, DeniedCall[playerid], 1);
	PlayerTextDrawSetProportional(playerid, DeniedCall[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, DeniedCall[playerid], 1);

	PlayerTD[playerid][0] = CreatePlayerTextDraw(playerid, 184.000000, 288.000000, "_");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][0], 1);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][0], 0.600000, 0.399998);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][0], 298.500000, 75.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][0], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][0], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][0], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][0], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][0], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][0], 135);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][0], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][0], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][0], 0);

	BatteryTD[playerid] = CreatePlayerTextDraw(playerid, 214.000000, 290.000000, "_");
	PlayerTextDrawFont(playerid, BatteryTD[playerid], 0);
	PlayerTextDrawLetterSize(playerid, BatteryTD[playerid], 0.600000, -0.049998);
	PlayerTextDrawTextSize(playerid, BatteryTD[playerid], 298.500000, -11.500000);
	PlayerTextDrawSetOutline(playerid, BatteryTD[playerid], 1);
	PlayerTextDrawSetShadow(playerid, BatteryTD[playerid], 0);
	PlayerTextDrawAlignment(playerid, BatteryTD[playerid], 2);
	PlayerTextDrawColor(playerid, BatteryTD[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, BatteryTD[playerid], 255);
	PlayerTextDrawBoxColor(playerid, BatteryTD[playerid], -1);
	PlayerTextDrawUseBox(playerid, BatteryTD[playerid], 1);
	PlayerTextDrawSetProportional(playerid, BatteryTD[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, BatteryTD[playerid], 0);

	PhoneNumber[playerid] = CreatePlayerTextDraw(playerid, 149.000000, 287.500000, "No Card");
	PlayerTextDrawFont(playerid, PhoneNumber[playerid], 1);
	PlayerTextDrawLetterSize(playerid, PhoneNumber[playerid], 0.100000, 0.549996);
	PlayerTextDrawTextSize(playerid, PhoneNumber[playerid], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PhoneNumber[playerid], 1);
	PlayerTextDrawSetShadow(playerid, PhoneNumber[playerid], 0);
	PlayerTextDrawAlignment(playerid, PhoneNumber[playerid], 1);
	PlayerTextDrawColor(playerid, PhoneNumber[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, PhoneNumber[playerid], 255);
	PlayerTextDrawBoxColor(playerid, PhoneNumber[playerid], 50);
	PlayerTextDrawUseBox(playerid, PhoneNumber[playerid], 0);
	PlayerTextDrawSetProportional(playerid, PhoneNumber[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneNumber[playerid], 0);

	Battery[playerid] = CreatePlayerTextDraw(playerid, 211.000000, 287.799987, "100");
	PlayerTextDrawFont(playerid, Battery[playerid], 1);
	PlayerTextDrawLetterSize(playerid, Battery[playerid], 0.087499, 0.399996);
	PlayerTextDrawTextSize(playerid, Battery[playerid], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, Battery[playerid], 0);
	PlayerTextDrawSetShadow(playerid, Battery[playerid], 0);
	PlayerTextDrawAlignment(playerid, Battery[playerid], 1);
	PlayerTextDrawColor(playerid, Battery[playerid], 255);
	PlayerTextDrawBackgroundColor(playerid, Battery[playerid], 255);
	PlayerTextDrawBoxColor(playerid, Battery[playerid], 50);
	PlayerTextDrawUseBox(playerid, Battery[playerid], 0);
	PlayerTextDrawSetProportional(playerid, Battery[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, Battery[playerid], 0);

	return 1;
}

public OnPlayerDisconnect(playerid, reason)
{
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][0]);
	PlayerTextDrawDestroy(playerid, BOX1[playerid]);
	PlayerTextDrawDestroy(playerid, BOX2[playerid]);
	PlayerTextDrawDestroy(playerid, ScreenBG[playerid]);
	PlayerTextDrawDestroy(playerid, BOX3[playerid]);
	PlayerTextDrawDestroy(playerid, MidButton[playerid]);
	PlayerTextDrawDestroy(playerid, IncomingNumber[playerid]);
	PlayerTextDrawDestroy(playerid, IncomingCall[playerid]);
	PlayerTextDrawDestroy(playerid, AcceptCall[playerid]);
	PlayerTextDrawDestroy(playerid, DeniedCall[playerid]);
	PlayerTextDrawDestroy(playerid, BatteryTD[playerid]);
	PlayerTextDrawDestroy(playerid, PhoneNumber[playerid]);
	PlayerTextDrawDestroy(playerid, Battery[playerid]);
	return 1;
}

public OnPlayerCommandText(playerid, cmdtext[])
{
	if(!strcmp(cmdtext, "/tdtest", true))
	{
		PlayerTextDrawShow(playerid, PlayerTD[playerid][0]);
		PlayerTextDrawShow(playerid, BOX1[playerid]);
		PlayerTextDrawShow(playerid, BOX2[playerid]);
		PlayerTextDrawShow(playerid, ScreenBG[playerid]);
		PlayerTextDrawShow(playerid, BOX3[playerid]);
		PlayerTextDrawShow(playerid, MidButton[playerid]);
		PlayerTextDrawShow(playerid, IncomingNumber[playerid]);
		PlayerTextDrawShow(playerid, IncomingCall[playerid]);
		PlayerTextDrawShow(playerid, AcceptCall[playerid]);
		PlayerTextDrawShow(playerid, DeniedCall[playerid]);
		PlayerTextDrawShow(playerid, BatteryTD[playerid]);
		PlayerTextDrawShow(playerid, PhoneNumber[playerid]);
		PlayerTextDrawShow(playerid, Battery[playerid]);
		SelectTextDraw(playerid, 0xFF0000FF);
		return 1;
	}
	return 0;
}
