/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

#include <a_samp>

new Text:PublicTD[1];

public OnFilterScriptInit()
{
	PublicTD[0] = TextDrawCreate(250.000000, 150.000000, "Preview_Model");
	TextDrawFont(PublicTD[0], 5);
	TextDrawLetterSize(PublicTD[0], 0.600000, 2.000000);
	TextDrawTextSize(PublicTD[0], 112.500000, 150.000000);
	TextDrawSetOutline(PublicTD[0], 0);
	TextDrawSetShadow(PublicTD[0], 0);
	TextDrawAlignment(PublicTD[0], 1);
	TextDrawColor(PublicTD[0], -1);
	TextDrawBackgroundColor(PublicTD[0], 125);
	TextDrawBoxColor(PublicTD[0], 255);
	TextDrawUseBox(PublicTD[0], 0);
	TextDrawSetProportional(PublicTD[0], 1);
	TextDrawSetSelectable(PublicTD[0], 0);
	TextDrawSetPreviewModel(PublicTD[0], -2001);
	TextDrawSetPreviewRot(PublicTD[0], -15.000000, 1.000000, -92.000000, 1.000000);
	TextDrawSetPreviewVehCol(PublicTD[0], 1, 1);

	return 1;
}

public OnFilterScriptExit()
{
	TextDrawDestroy(PublicTD[0]);
	return 1;
}

public OnPlayerConnect(playerid)
{
	return 1;
}

public OnPlayerDisconnect(playerid, reason)
{
	return 1;
}

public OnPlayerCommandText(playerid, cmdtext[])
{
	if(!strcmp(cmdtext, "/tdtest", true))
	{
		TextDrawShowForPlayer(playerid, PublicTD[0]);
		return 1;
	}
	return 0;
}
