/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

#include <a_samp>
#include <progress2>
//Requires "progress2" include by Southclaws
//Download: https://github.com/Southclaws/progress2/releases

new PlayerText:PlayerTD[MAX_PLAYERS][5];
new PlayerBar:PlayerProgressBar[MAX_PLAYERS][3];

public OnFilterScriptInit()
{
	return 1;
}

public OnFilterScriptExit()
{
	return 1;
}

public OnPlayerConnect(playerid)
{
    // PlayerTD[playerid][0] = CreatePlayerTextDraw(playerid, 401.500000, 376.500061, "I");
    // PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][0], 27.443979, 9.488110);
    // PlayerTextDrawAlignment(playerid, PlayerTD[playerid][0], 1);
    // PlayerTextDrawColor(playerid, PlayerTD[playerid][0], 133);
    // PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][0], 0);
    // PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][0], 0);
    // PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][0], 255);
    // PlayerTextDrawFont(playerid, PlayerTD[playerid][0], 2);
    // PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][0], 1);
    // PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][0], 0);

	PlayerTD[playerid][1] = CreatePlayerTextDraw(playerid, 548.000000, 433.500000, "HUD:radar_diner");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][1], 4);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][1], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][1], 10.000000, 9.500000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][1], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][1], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][1], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][1], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][1], 0);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][1], 0);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][1], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][1], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][1], 1);

	PlayerTD[playerid][2] = CreatePlayerTextDraw(playerid, 547.000000, 406.000000, "HUD:radar_datefood");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][2], 4);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][2], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][2], 10.000000, 9.500000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][2], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][2], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][2], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][2], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][2], 0);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][2], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][2], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][2], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][2], 0);

	PlayerTD[playerid][3] = CreatePlayerTextDraw(playerid, 547.000000, 419.000000, "HUD:radar_centre");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][3], 4);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][3], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][3], 10.000000, 9.500000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][3], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][3], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][3], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][3], 16777215);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][3], 0);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][3], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][3], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][3], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][3], 0);

	PlayerTD[playerid][4] = CreatePlayerTextDraw(playerid, 499.500000, 400.000000, "");
    PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][4], 0.000000, 0.000000);
    PlayerTextDrawTextSize(playerid, PlayerTD[playerid][4], 69.000000, 50.000000);
    PlayerTextDrawAlignment(playerid, PlayerTD[playerid][4], 1);
    PlayerTextDrawColor(playerid, PlayerTD[playerid][4], -1);
    PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][4], 0);
    PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][4], 0);
    PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][4], 0);
    PlayerTextDrawFont(playerid, PlayerTD[playerid][4], 5);
    PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][4], 0);
    PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][4], 0);
    PlayerTextDrawSetPreviewModel(playerid, PlayerTD[playerid][4], 3);
    PlayerTextDrawSetPreviewRot(playerid, PlayerTD[playerid][4], 0.000000, 0.000000, 0.000000, 1.000000);

	PlayerProgressBar[playerid][0] = CreatePlayerProgressBar(playerid, 560.000000, 408.500000, 51.000000, 4.000000, 852308650, 100.000000, 0);
	SetPlayerProgressBarValue(playerid, PlayerProgressBar[playerid][0], 50.000000);

	PlayerProgressBar[playerid][1] = CreatePlayerProgressBar(playerid, 560.000000, 422.000000, 51.000000, 4.000000, 852308650, 100.000000, 0);
	SetPlayerProgressBarValue(playerid, PlayerProgressBar[playerid][1], 50.000000);

	PlayerProgressBar[playerid][2] = CreatePlayerProgressBar(playerid, 560.000000, 436.000000, 51.000000, 4.000000, 852308650, 100.000000, 0);
	SetPlayerProgressBarValue(playerid, PlayerProgressBar[playerid][2], 50.000000);

	return 1;
}

public OnPlayerDisconnect(playerid, reason)
{
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][0]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][1]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][2]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][3]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][4]);
	DestroyPlayerProgressBar(playerid, PlayerProgressBar[playerid][0]);
	DestroyPlayerProgressBar(playerid, PlayerProgressBar[playerid][1]);
	DestroyPlayerProgressBar(playerid, PlayerProgressBar[playerid][2]);
	return 1;
}

public OnPlayerCommandText(playerid, cmdtext[])
{
	if(!strcmp(cmdtext, "/tdtest", true))
	{
		PlayerTextDrawShow(playerid, PlayerTD[playerid][0]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][1]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][2]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][3]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][4]);
		ShowPlayerProgressBar(playerid, PlayerProgressBar[playerid][0]);
		ShowPlayerProgressBar(playerid, PlayerProgressBar[playerid][1]);
		ShowPlayerProgressBar(playerid, PlayerProgressBar[playerid][2]);
		return 1;
	}
	return 0;
}
