/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

#include <a_samp>

new PlayerText:PlayerTD[MAX_PLAYERS][11];
new PlayerText:BG_BOX_0[MAX_PLAYERS];
new PlayerText:Gambar_Kendaraan[MAX_PLAYERS];
new PlayerText:Garis_0[MAX_PLAYERS];
new PlayerText:Vehiclename[MAX_PLAYERS];

public OnFilterScriptInit()
{
	return 1;
}

public OnFilterScriptExit()
{
	return 1;
}

public OnPlayerConnect(playerid)
{
	BG_BOX_0[playerid] = CreatePlayerTextDraw(playerid, 554.000000, 312.000000, "_");
	PlayerTextDrawFont(playerid, BG_BOX_0[playerid], 1);
	PlayerTextDrawLetterSize(playerid, BG_BOX_0[playerid], 0.600000, 5.249999);
	PlayerTextDrawTextSize(playerid, BG_BOX_0[playerid], 298.500000, 164.500000);
	PlayerTextDrawSetOutline(playerid, BG_BOX_0[playerid], 1);
	PlayerTextDrawSetShadow(playerid, BG_BOX_0[playerid], 0);
	PlayerTextDrawAlignment(playerid, BG_BOX_0[playerid], 2);
	PlayerTextDrawColor(playerid, BG_BOX_0[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, BG_BOX_0[playerid], 255);
	PlayerTextDrawBoxColor(playerid, BG_BOX_0[playerid], 105);
	PlayerTextDrawUseBox(playerid, BG_BOX_0[playerid], 1);
	PlayerTextDrawSetProportional(playerid, BG_BOX_0[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, BG_BOX_0[playerid], 0);

	Gambar_Kendaraan[playerid] = CreatePlayerTextDraw(playerid, 567.000000, 279.000000, "Preview_Model");
	PlayerTextDrawFont(playerid, Gambar_Kendaraan[playerid], 5);
	PlayerTextDrawLetterSize(playerid, Gambar_Kendaraan[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, Gambar_Kendaraan[playerid], 80.500000, 90.000000);
	PlayerTextDrawSetOutline(playerid, Gambar_Kendaraan[playerid], 0);
	PlayerTextDrawSetShadow(playerid, Gambar_Kendaraan[playerid], 0);
	PlayerTextDrawAlignment(playerid, Gambar_Kendaraan[playerid], 1);
	PlayerTextDrawColor(playerid, Gambar_Kendaraan[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, Gambar_Kendaraan[playerid], 0);
	PlayerTextDrawBoxColor(playerid, Gambar_Kendaraan[playerid], 255);
	PlayerTextDrawUseBox(playerid, Gambar_Kendaraan[playerid], 0);
	PlayerTextDrawSetProportional(playerid, Gambar_Kendaraan[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, Gambar_Kendaraan[playerid], 0);
	PlayerTextDrawSetPreviewModel(playerid, Gambar_Kendaraan[playerid], 541);
	PlayerTextDrawSetPreviewRot(playerid, Gambar_Kendaraan[playerid], -10.000000, 0.000000, -42.000000, 1.000000);
	PlayerTextDrawSetPreviewVehCol(playerid, Gambar_Kendaraan[playerid], 1, 1);

	Garis_0[playerid] = CreatePlayerTextDraw(playerid, 475.000000, 323.000000, "-");
	PlayerTextDrawFont(playerid, Garis_0[playerid], 3);
	PlayerTextDrawLetterSize(playerid, Garis_0[playerid], 6.970827, 0.549997);
	PlayerTextDrawTextSize(playerid, Garis_0[playerid], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, Garis_0[playerid], 1);
	PlayerTextDrawSetShadow(playerid, Garis_0[playerid], 0);
	PlayerTextDrawAlignment(playerid, Garis_0[playerid], 1);
	PlayerTextDrawColor(playerid, Garis_0[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, Garis_0[playerid], 255);
	PlayerTextDrawBoxColor(playerid, Garis_0[playerid], 50);
	PlayerTextDrawUseBox(playerid, Garis_0[playerid], 0);
	PlayerTextDrawSetProportional(playerid, Garis_0[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, Garis_0[playerid], 0);

	Vehiclename[playerid] = CreatePlayerTextDraw(playerid, 509.000000, 312.000000, "Bullet");
	PlayerTextDrawFont(playerid, Vehiclename[playerid], 0);
	PlayerTextDrawLetterSize(playerid, Vehiclename[playerid], 0.425000, 1.200000);
	PlayerTextDrawTextSize(playerid, Vehiclename[playerid], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, Vehiclename[playerid], 1);
	PlayerTextDrawSetShadow(playerid, Vehiclename[playerid], 0);
	PlayerTextDrawAlignment(playerid, Vehiclename[playerid], 1);
	PlayerTextDrawColor(playerid, Vehiclename[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, Vehiclename[playerid], 255);
	PlayerTextDrawBoxColor(playerid, Vehiclename[playerid], 50);
	PlayerTextDrawUseBox(playerid, Vehiclename[playerid], 0);
	PlayerTextDrawSetProportional(playerid, Vehiclename[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, Vehiclename[playerid], 0);

	PlayerTD[playerid][0] = CreatePlayerTextDraw(playerid, 474.000000, 349.000000, "TRANSMISSION");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][0], 2);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][0], 0.125000, 0.750000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][0], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][0], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][0], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][0], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][0], 16777215);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][0], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][0], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][0], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][0], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][0], 0);

	PlayerTD[playerid][1] = CreatePlayerTextDraw(playerid, 474.000000, 339.500000, "FUEL");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][1], 2);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][1], 0.125000, 0.750000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][1], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][1], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][1], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][1], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][1], 16777215);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][1], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][1], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][1], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][1], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][1], 0);

	PlayerTD[playerid][2] = CreatePlayerTextDraw(playerid, 474.000000, 330.000000, "DAMAGE");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][2], 2);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][2], 0.125000, 0.750000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][2], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][2], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][2], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][2], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][2], 16777215);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][2], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][2], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][2], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][2], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][2], 0);

	PlayerTD[playerid][3] = CreatePlayerTextDraw(playerid, 513.000000, 330.000000, ":");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][3], 2);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][3], 0.125000, 0.750000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][3], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][3], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][3], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][3], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][3], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][3], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][3], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][3], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][3], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][3], 0);

	PlayerTD[playerid][4] = CreatePlayerTextDraw(playerid, 513.000000, 339.500000, ":");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][4], 2);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][4], 0.125000, 0.750000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][4], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][4], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][4], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][4], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][4], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][4], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][4], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][4], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][4], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][4], 0);

	PlayerTD[playerid][5] = CreatePlayerTextDraw(playerid, 513.000000, 349.000000, ":");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][5], 2);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][5], 0.125000, 0.750000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][5], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][5], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][5], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][5], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][5], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][5], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][5], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][5], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][5], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][5], 0);

	PlayerTD[playerid][6] = CreatePlayerTextDraw(playerid, 517.000000, 330.000000, "1000/1000");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][6], 2);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][6], 0.125000, 0.750000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][6], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][6], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][6], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][6], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][6], 16711935);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][6], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][6], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][6], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][6], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][6], 0);

	PlayerTD[playerid][7] = CreatePlayerTextDraw(playerid, 517.000000, 339.500000, "100%");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][7], 2);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][7], 0.125000, 0.750000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][7], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][7], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][7], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][7], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][7], 16711935);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][7], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][7], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][7], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][7], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][7], 0);

	PlayerTD[playerid][8] = CreatePlayerTextDraw(playerid, 517.000000, 349.000000, "R N D");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][8], 2);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][8], 0.125000, 0.750000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][8], 530.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][8], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][8], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][8], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][8], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][8], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][8], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][8], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][8], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][8], 0);

	PlayerTD[playerid][9] = CreatePlayerTextDraw(playerid, 557.000000, 342.500000, "125");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][9], 2);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][9], 0.375000, 1.849997);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][9], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][9], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][9], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][9], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][9], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][9], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][9], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][9], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][9], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][9], 0);

	PlayerTD[playerid][10] = CreatePlayerTextDraw(playerid, 588.000000, 342.500000, "KM/H");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][10], 2);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][10], 0.375000, 1.849997);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][10], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][10], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][10], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][10], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][10], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][10], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][10], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][10], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][10], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][10], 0);

	return 1;
}

public OnPlayerDisconnect(playerid, reason)
{
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][0]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][1]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][2]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][3]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][4]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][5]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][6]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][7]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][8]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][9]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][10]);
	PlayerTextDrawDestroy(playerid, BG_BOX_0[playerid]);
	PlayerTextDrawDestroy(playerid, Gambar_Kendaraan[playerid]);
	PlayerTextDrawDestroy(playerid, Garis_0[playerid]);
	PlayerTextDrawDestroy(playerid, Vehiclename[playerid]);
	return 1;
}

public OnPlayerCommandText(playerid, cmdtext[])
{
	if(!strcmp(cmdtext, "/tdtest", true))
	{
		PlayerTextDrawShow(playerid, PlayerTD[playerid][0]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][1]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][2]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][3]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][4]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][5]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][6]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][7]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][8]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][9]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][10]);
		PlayerTextDrawShow(playerid, BG_BOX_0[playerid]);
		PlayerTextDrawShow(playerid, Gambar_Kendaraan[playerid]);
		PlayerTextDrawShow(playerid, Garis_0[playerid]);
		PlayerTextDrawShow(playerid, Vehiclename[playerid]);
		return 1;
	}
	return 0;
}
