/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

#include <a_samp>
#include <progress2>
//Requires "progress2" include by Southclaws
//Download: https://github.com/Southclaws/progress2/releases

new PlayerText:Main_Box[MAX_PLAYERS];
new PlayerText:Vehicle_Name[MAX_PLAYERS];
new PlayerText:Speed_Label[MAX_PLAYERS];
new PlayerText:Model_Preview[MAX_PLAYERS];
new PlayerText:Transmission_Label[MAX_PLAYERS];
new PlayerText:Damage_Label[MAX_PLAYERS];
new PlayerText:Speed_Separator[MAX_PLAYERS];
new PlayerText:Transmission_Separator[MAX_PLAYERS];
new PlayerText:Damage_Separator[MAX_PLAYERS];
new PlayerText:Speed_Value[MAX_PLAYERS];
new PlayerText:Mileage_Label[MAX_PLAYERS];
new PlayerText:Fuel_Label[MAX_PLAYERS];
new PlayerText:Mileage_Separator[MAX_PLAYERS];
new PlayerText:Transmission_Value[MAX_PLAYERS];
new PlayerText:Damage_Value[MAX_PLAYERS];
new PlayerText:Mileage_Value[MAX_PLAYERS];
new PlayerBar:Fuel_Bar[MAX_PLAYERS];

public OnFilterScriptInit()
{
	return 1;
}

public OnFilterScriptExit()
{
	return 1;
}

public OnPlayerConnect(playerid)
{
	Main_Box[playerid] = CreatePlayerTextDraw(playerid, 570.000000, 335.000000, "__");
	PlayerTextDrawFont(playerid, Main_Box[playerid], 1);
	PlayerTextDrawLetterSize(playerid, Main_Box[playerid], 0.600000, 7.149991);
	PlayerTextDrawTextSize(playerid, Main_Box[playerid], 298.500000, 139.500000);
	PlayerTextDrawSetOutline(playerid, Main_Box[playerid], 1);
	PlayerTextDrawSetShadow(playerid, Main_Box[playerid], 0);
	PlayerTextDrawAlignment(playerid, Main_Box[playerid], 2);
	PlayerTextDrawColor(playerid, Main_Box[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, Main_Box[playerid], 255);
	PlayerTextDrawBoxColor(playerid, Main_Box[playerid], 135);
	PlayerTextDrawUseBox(playerid, Main_Box[playerid], 1);
	PlayerTextDrawSetProportional(playerid, Main_Box[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, Main_Box[playerid], 0);

	Vehicle_Name[playerid] = CreatePlayerTextDraw(playerid, 570.000000, 321.000000, "Vehicle Name");
	PlayerTextDrawFont(playerid, Vehicle_Name[playerid], 2);
	PlayerTextDrawLetterSize(playerid, Vehicle_Name[playerid], 0.183329, 1.149999);
	PlayerTextDrawTextSize(playerid, Vehicle_Name[playerid], 405.000000, 139.500000);
	PlayerTextDrawSetOutline(playerid, Vehicle_Name[playerid], 0);
	PlayerTextDrawSetShadow(playerid, Vehicle_Name[playerid], 0);
	PlayerTextDrawAlignment(playerid, Vehicle_Name[playerid], 2);
	PlayerTextDrawColor(playerid, Vehicle_Name[playerid], -126);
	PlayerTextDrawBackgroundColor(playerid, Vehicle_Name[playerid], 255);
	PlayerTextDrawBoxColor(playerid, Vehicle_Name[playerid], 128);
	PlayerTextDrawUseBox(playerid, Vehicle_Name[playerid], 1);
	PlayerTextDrawSetProportional(playerid, Vehicle_Name[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, Vehicle_Name[playerid], 0);

	Speed_Label[playerid] = CreatePlayerTextDraw(playerid, 503.000000, 335.000000, "SPEED");
	PlayerTextDrawFont(playerid, Speed_Label[playerid], 2);
	PlayerTextDrawLetterSize(playerid, Speed_Label[playerid], 0.150000, 1.000000);
	PlayerTextDrawTextSize(playerid, Speed_Label[playerid], 773.000000, 20.500000);
	PlayerTextDrawSetOutline(playerid, Speed_Label[playerid], 0);
	PlayerTextDrawSetShadow(playerid, Speed_Label[playerid], 0);
	PlayerTextDrawAlignment(playerid, Speed_Label[playerid], 1);
	PlayerTextDrawColor(playerid, Speed_Label[playerid], 11150847);
	PlayerTextDrawBackgroundColor(playerid, Speed_Label[playerid], 255);
	PlayerTextDrawBoxColor(playerid, Speed_Label[playerid], 50);
	PlayerTextDrawUseBox(playerid, Speed_Label[playerid], 0);
	PlayerTextDrawSetProportional(playerid, Speed_Label[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, Speed_Label[playerid], 0);

	Model_Preview[playerid] = CreatePlayerTextDraw(playerid, 597.000000, 319.000000, "TextDraw");
	PlayerTextDrawFont(playerid, Model_Preview[playerid], 5);
	PlayerTextDrawLetterSize(playerid, Model_Preview[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, Model_Preview[playerid], 44.000000, 54.000000);
	PlayerTextDrawSetOutline(playerid, Model_Preview[playerid], 1);
	PlayerTextDrawSetShadow(playerid, Model_Preview[playerid], 0);
	PlayerTextDrawAlignment(playerid, Model_Preview[playerid], 1);
	PlayerTextDrawColor(playerid, Model_Preview[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, Model_Preview[playerid], 0);
	PlayerTextDrawBoxColor(playerid, Model_Preview[playerid], 0);
	PlayerTextDrawUseBox(playerid, Model_Preview[playerid], 1);
	PlayerTextDrawSetProportional(playerid, Model_Preview[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, Model_Preview[playerid], 0);
	PlayerTextDrawSetPreviewModel(playerid, Model_Preview[playerid], 400);
	PlayerTextDrawSetPreviewRot(playerid, Model_Preview[playerid], -8.000000, 3.000000, -47.000000, 0.799996);
	PlayerTextDrawSetPreviewVehCol(playerid, Model_Preview[playerid], 1, 1);

	Transmission_Label[playerid] = CreatePlayerTextDraw(playerid, 503.000000, 345.000000, "TRANSMISSION");
	PlayerTextDrawFont(playerid, Transmission_Label[playerid], 2);
	PlayerTextDrawLetterSize(playerid, Transmission_Label[playerid], 0.150000, 1.000000);
	PlayerTextDrawTextSize(playerid, Transmission_Label[playerid], 773.000000, 20.500000);
	PlayerTextDrawSetOutline(playerid, Transmission_Label[playerid], 0);
	PlayerTextDrawSetShadow(playerid, Transmission_Label[playerid], 0);
	PlayerTextDrawAlignment(playerid, Transmission_Label[playerid], 1);
	PlayerTextDrawColor(playerid, Transmission_Label[playerid], 11150847);
	PlayerTextDrawBackgroundColor(playerid, Transmission_Label[playerid], 255);
	PlayerTextDrawBoxColor(playerid, Transmission_Label[playerid], 50);
	PlayerTextDrawUseBox(playerid, Transmission_Label[playerid], 0);
	PlayerTextDrawSetProportional(playerid, Transmission_Label[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, Transmission_Label[playerid], 0);

	Damage_Label[playerid] = CreatePlayerTextDraw(playerid, 503.000000, 355.000000, "DAMAGE");
	PlayerTextDrawFont(playerid, Damage_Label[playerid], 2);
	PlayerTextDrawLetterSize(playerid, Damage_Label[playerid], 0.150000, 1.000000);
	PlayerTextDrawTextSize(playerid, Damage_Label[playerid], 773.000000, 20.500000);
	PlayerTextDrawSetOutline(playerid, Damage_Label[playerid], 0);
	PlayerTextDrawSetShadow(playerid, Damage_Label[playerid], 0);
	PlayerTextDrawAlignment(playerid, Damage_Label[playerid], 1);
	PlayerTextDrawColor(playerid, Damage_Label[playerid], 11150847);
	PlayerTextDrawBackgroundColor(playerid, Damage_Label[playerid], 255);
	PlayerTextDrawBoxColor(playerid, Damage_Label[playerid], 50);
	PlayerTextDrawUseBox(playerid, Damage_Label[playerid], 0);
	PlayerTextDrawSetProportional(playerid, Damage_Label[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, Damage_Label[playerid], 0);

	Speed_Separator[playerid] = CreatePlayerTextDraw(playerid, 550.000000, 334.000000, ":");
	PlayerTextDrawFont(playerid, Speed_Separator[playerid], 2);
	PlayerTextDrawLetterSize(playerid, Speed_Separator[playerid], 0.150000, 1.000000);
	PlayerTextDrawTextSize(playerid, Speed_Separator[playerid], 773.000000, 20.500000);
	PlayerTextDrawSetOutline(playerid, Speed_Separator[playerid], 0);
	PlayerTextDrawSetShadow(playerid, Speed_Separator[playerid], 0);
	PlayerTextDrawAlignment(playerid, Speed_Separator[playerid], 1);
	PlayerTextDrawColor(playerid, Speed_Separator[playerid], 11150847);
	PlayerTextDrawBackgroundColor(playerid, Speed_Separator[playerid], 255);
	PlayerTextDrawBoxColor(playerid, Speed_Separator[playerid], 50);
	PlayerTextDrawUseBox(playerid, Speed_Separator[playerid], 0);
	PlayerTextDrawSetProportional(playerid, Speed_Separator[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, Speed_Separator[playerid], 0);

	Transmission_Separator[playerid] = CreatePlayerTextDraw(playerid, 550.000000, 344.000000, ":");
	PlayerTextDrawFont(playerid, Transmission_Separator[playerid], 2);
	PlayerTextDrawLetterSize(playerid, Transmission_Separator[playerid], 0.150000, 1.000000);
	PlayerTextDrawTextSize(playerid, Transmission_Separator[playerid], 773.000000, 20.500000);
	PlayerTextDrawSetOutline(playerid, Transmission_Separator[playerid], 0);
	PlayerTextDrawSetShadow(playerid, Transmission_Separator[playerid], 0);
	PlayerTextDrawAlignment(playerid, Transmission_Separator[playerid], 1);
	PlayerTextDrawColor(playerid, Transmission_Separator[playerid], 11150847);
	PlayerTextDrawBackgroundColor(playerid, Transmission_Separator[playerid], 255);
	PlayerTextDrawBoxColor(playerid, Transmission_Separator[playerid], 50);
	PlayerTextDrawUseBox(playerid, Transmission_Separator[playerid], 0);
	PlayerTextDrawSetProportional(playerid, Transmission_Separator[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, Transmission_Separator[playerid], 0);

	Damage_Separator[playerid] = CreatePlayerTextDraw(playerid, 550.000000, 354.000000, ":");
	PlayerTextDrawFont(playerid, Damage_Separator[playerid], 2);
	PlayerTextDrawLetterSize(playerid, Damage_Separator[playerid], 0.150000, 1.000000);
	PlayerTextDrawTextSize(playerid, Damage_Separator[playerid], 773.000000, 20.500000);
	PlayerTextDrawSetOutline(playerid, Damage_Separator[playerid], 0);
	PlayerTextDrawSetShadow(playerid, Damage_Separator[playerid], 0);
	PlayerTextDrawAlignment(playerid, Damage_Separator[playerid], 1);
	PlayerTextDrawColor(playerid, Damage_Separator[playerid], 11150847);
	PlayerTextDrawBackgroundColor(playerid, Damage_Separator[playerid], 255);
	PlayerTextDrawBoxColor(playerid, Damage_Separator[playerid], 50);
	PlayerTextDrawUseBox(playerid, Damage_Separator[playerid], 0);
	PlayerTextDrawSetProportional(playerid, Damage_Separator[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, Damage_Separator[playerid], 0);

	Speed_Value[playerid] = CreatePlayerTextDraw(playerid, 557.000000, 334.000000, "999 KMH");
	PlayerTextDrawFont(playerid, Speed_Value[playerid], 2);
	PlayerTextDrawLetterSize(playerid, Speed_Value[playerid], 0.150000, 1.000000);
	PlayerTextDrawTextSize(playerid, Speed_Value[playerid], 773.000000, 20.500000);
	PlayerTextDrawSetOutline(playerid, Speed_Value[playerid], 0);
	PlayerTextDrawSetShadow(playerid, Speed_Value[playerid], 0);
	PlayerTextDrawAlignment(playerid, Speed_Value[playerid], 1);
	PlayerTextDrawColor(playerid, Speed_Value[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, Speed_Value[playerid], 255);
	PlayerTextDrawBoxColor(playerid, Speed_Value[playerid], 50);
	PlayerTextDrawUseBox(playerid, Speed_Value[playerid], 0);
	PlayerTextDrawSetProportional(playerid, Speed_Value[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, Speed_Value[playerid], 0);

	Mileage_Label[playerid] = CreatePlayerTextDraw(playerid, 503.000000, 365.000000, "MILEAGE");
	PlayerTextDrawFont(playerid, Mileage_Label[playerid], 2);
	PlayerTextDrawLetterSize(playerid, Mileage_Label[playerid], 0.150000, 1.000000);
	PlayerTextDrawTextSize(playerid, Mileage_Label[playerid], 773.000000, 20.500000);
	PlayerTextDrawSetOutline(playerid, Mileage_Label[playerid], 0);
	PlayerTextDrawSetShadow(playerid, Mileage_Label[playerid], 0);
	PlayerTextDrawAlignment(playerid, Mileage_Label[playerid], 1);
	PlayerTextDrawColor(playerid, Mileage_Label[playerid], 11150847);
	PlayerTextDrawBackgroundColor(playerid, Mileage_Label[playerid], 255);
	PlayerTextDrawBoxColor(playerid, Mileage_Label[playerid], 50);
	PlayerTextDrawUseBox(playerid, Mileage_Label[playerid], 0);
	PlayerTextDrawSetProportional(playerid, Mileage_Label[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, Mileage_Label[playerid], 0);

	Fuel_Label[playerid] = CreatePlayerTextDraw(playerid, 503.000000, 375.000000, "FUEL");
	PlayerTextDrawFont(playerid, Fuel_Label[playerid], 2);
	PlayerTextDrawLetterSize(playerid, Fuel_Label[playerid], 0.150000, 1.000000);
	PlayerTextDrawTextSize(playerid, Fuel_Label[playerid], 773.000000, 20.500000);
	PlayerTextDrawSetOutline(playerid, Fuel_Label[playerid], 0);
	PlayerTextDrawSetShadow(playerid, Fuel_Label[playerid], 0);
	PlayerTextDrawAlignment(playerid, Fuel_Label[playerid], 1);
	PlayerTextDrawColor(playerid, Fuel_Label[playerid], 11150847);
	PlayerTextDrawBackgroundColor(playerid, Fuel_Label[playerid], 255);
	PlayerTextDrawBoxColor(playerid, Fuel_Label[playerid], 50);
	PlayerTextDrawUseBox(playerid, Fuel_Label[playerid], 0);
	PlayerTextDrawSetProportional(playerid, Fuel_Label[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, Fuel_Label[playerid], 0);

	Mileage_Separator[playerid] = CreatePlayerTextDraw(playerid, 550.000000, 364.000000, ":");
	PlayerTextDrawFont(playerid, Mileage_Separator[playerid], 2);
	PlayerTextDrawLetterSize(playerid, Mileage_Separator[playerid], 0.150000, 1.000000);
	PlayerTextDrawTextSize(playerid, Mileage_Separator[playerid], 773.000000, 20.500000);
	PlayerTextDrawSetOutline(playerid, Mileage_Separator[playerid], 0);
	PlayerTextDrawSetShadow(playerid, Mileage_Separator[playerid], 0);
	PlayerTextDrawAlignment(playerid, Mileage_Separator[playerid], 1);
	PlayerTextDrawColor(playerid, Mileage_Separator[playerid], 11150847);
	PlayerTextDrawBackgroundColor(playerid, Mileage_Separator[playerid], 255);
	PlayerTextDrawBoxColor(playerid, Mileage_Separator[playerid], 50);
	PlayerTextDrawUseBox(playerid, Mileage_Separator[playerid], 0);
	PlayerTextDrawSetProportional(playerid, Mileage_Separator[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, Mileage_Separator[playerid], 0);

	Transmission_Value[playerid] = CreatePlayerTextDraw(playerid, 557.000000, 344.000000, "~r~R ~r~~h~~h~R ~b~N ~b~~h~~h~N ~g~D ~g~~h~~h~D");
	PlayerTextDrawFont(playerid, Transmission_Value[playerid], 2);
	PlayerTextDrawLetterSize(playerid, Transmission_Value[playerid], 0.150000, 1.000000);
	PlayerTextDrawTextSize(playerid, Transmission_Value[playerid], 773.000000, 20.500000);
	PlayerTextDrawSetOutline(playerid, Transmission_Value[playerid], 1);
	PlayerTextDrawSetShadow(playerid, Transmission_Value[playerid], 0);
	PlayerTextDrawAlignment(playerid, Transmission_Value[playerid], 1);
	PlayerTextDrawColor(playerid, Transmission_Value[playerid], 852308735);
	PlayerTextDrawBackgroundColor(playerid, Transmission_Value[playerid], 255);
	PlayerTextDrawBoxColor(playerid, Transmission_Value[playerid], 50);
	PlayerTextDrawUseBox(playerid, Transmission_Value[playerid], 0);
	PlayerTextDrawSetProportional(playerid, Transmission_Value[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, Transmission_Value[playerid], 0);

	Damage_Value[playerid] = CreatePlayerTextDraw(playerid, 557.000000, 354.000000, "9999 / 9999");
	PlayerTextDrawFont(playerid, Damage_Value[playerid], 2);
	PlayerTextDrawLetterSize(playerid, Damage_Value[playerid], 0.150000, 1.000000);
	PlayerTextDrawTextSize(playerid, Damage_Value[playerid], 773.000000, 20.500000);
	PlayerTextDrawSetOutline(playerid, Damage_Value[playerid], 0);
	PlayerTextDrawSetShadow(playerid, Damage_Value[playerid], 0);
	PlayerTextDrawAlignment(playerid, Damage_Value[playerid], 1);
	PlayerTextDrawColor(playerid, Damage_Value[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, Damage_Value[playerid], 255);
	PlayerTextDrawBoxColor(playerid, Damage_Value[playerid], 50);
	PlayerTextDrawUseBox(playerid, Damage_Value[playerid], 0);
	PlayerTextDrawSetProportional(playerid, Damage_Value[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, Damage_Value[playerid], 0);

	Mileage_Value[playerid] = CreatePlayerTextDraw(playerid, 557.000000, 364.000000, "99.999 / 99.999");
	PlayerTextDrawFont(playerid, Mileage_Value[playerid], 2);
	PlayerTextDrawLetterSize(playerid, Mileage_Value[playerid], 0.150000, 1.000000);
	PlayerTextDrawTextSize(playerid, Mileage_Value[playerid], 773.000000, 20.500000);
	PlayerTextDrawSetOutline(playerid, Mileage_Value[playerid], 0);
	PlayerTextDrawSetShadow(playerid, Mileage_Value[playerid], 0);
	PlayerTextDrawAlignment(playerid, Mileage_Value[playerid], 1);
	PlayerTextDrawColor(playerid, Mileage_Value[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, Mileage_Value[playerid], 255);
	PlayerTextDrawBoxColor(playerid, Mileage_Value[playerid], 50);
	PlayerTextDrawUseBox(playerid, Mileage_Value[playerid], 0);
	PlayerTextDrawSetProportional(playerid, Mileage_Value[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, Mileage_Value[playerid], 0);

	Fuel_Bar[playerid] = CreatePlayerProgressBar(playerid, 503.000000, 390.000000, 137.500000, 5.500000, 11150847, 100.000000, 0);
	SetPlayerProgressBarValue(playerid, Fuel_Bar[playerid], 50.000000);

	return 1;
}

public OnPlayerDisconnect(playerid, reason)
{
	PlayerTextDrawDestroy(playerid, Main_Box[playerid]);
	PlayerTextDrawDestroy(playerid, Vehicle_Name[playerid]);
	PlayerTextDrawDestroy(playerid, Speed_Label[playerid]);
	PlayerTextDrawDestroy(playerid, Model_Preview[playerid]);
	PlayerTextDrawDestroy(playerid, Transmission_Label[playerid]);
	PlayerTextDrawDestroy(playerid, Damage_Label[playerid]);
	PlayerTextDrawDestroy(playerid, Speed_Separator[playerid]);
	PlayerTextDrawDestroy(playerid, Transmission_Separator[playerid]);
	PlayerTextDrawDestroy(playerid, Damage_Separator[playerid]);
	PlayerTextDrawDestroy(playerid, Speed_Value[playerid]);
	PlayerTextDrawDestroy(playerid, Mileage_Label[playerid]);
	PlayerTextDrawDestroy(playerid, Fuel_Label[playerid]);
	PlayerTextDrawDestroy(playerid, Mileage_Separator[playerid]);
	PlayerTextDrawDestroy(playerid, Transmission_Value[playerid]);
	PlayerTextDrawDestroy(playerid, Damage_Value[playerid]);
	PlayerTextDrawDestroy(playerid, Mileage_Value[playerid]);
	DestroyPlayerProgressBar(playerid, Fuel_Bar[playerid]);
	return 1;
}

public OnPlayerCommandText(playerid, cmdtext[])
{
	if(!strcmp(cmdtext, "/tdtest", true))
	{
		PlayerTextDrawShow(playerid, Main_Box[playerid]);
		PlayerTextDrawShow(playerid, Vehicle_Name[playerid]);
		PlayerTextDrawShow(playerid, Speed_Label[playerid]);
		PlayerTextDrawShow(playerid, Model_Preview[playerid]);
		PlayerTextDrawShow(playerid, Transmission_Label[playerid]);
		PlayerTextDrawShow(playerid, Damage_Label[playerid]);
		PlayerTextDrawShow(playerid, Speed_Separator[playerid]);
		PlayerTextDrawShow(playerid, Transmission_Separator[playerid]);
		PlayerTextDrawShow(playerid, Damage_Separator[playerid]);
		PlayerTextDrawShow(playerid, Speed_Value[playerid]);
		PlayerTextDrawShow(playerid, Mileage_Label[playerid]);
		PlayerTextDrawShow(playerid, Fuel_Label[playerid]);
		PlayerTextDrawShow(playerid, Mileage_Separator[playerid]);
		PlayerTextDrawShow(playerid, Transmission_Value[playerid]);
		PlayerTextDrawShow(playerid, Damage_Value[playerid]);
		PlayerTextDrawShow(playerid, Mileage_Value[playerid]);
		ShowPlayerProgressBar(playerid, Fuel_Bar[playerid]);
		return 1;
	}
	return 0;
}
