/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

#include <a_samp>

new PlayerText:BlackBarTOP[MAX_PLAYERS];
new PlayerText:BlackBarBOT[MAX_PLAYERS];
new PlayerText:LSNText[MAX_PLAYERS];
new PlayerText:LiveICON[MAX_PLAYERS];
new PlayerText:LeaveStreamButton[MAX_PLAYERS];
new PlayerText:LiveText[MAX_PLAYERS];
new PlayerText:ViewersText[MAX_PLAYERS];
new PlayerText:TotalViewers[MAX_PLAYERS];

public OnFilterScriptInit()
{
	return 1;
}

public OnFilterScriptExit()
{
	return 1;
}

public OnPlayerConnect(playerid)
{
	BlackBarTOP[playerid] = CreatePlayerTextDraw(playerid, 320.000000, 1.000000, "_");
	PlayerTextDrawFont(playerid, BlackBarTOP[playerid], 1);
	PlayerTextDrawLetterSize(playerid, BlackBarTOP[playerid], 0.600000, 2.950001);
	PlayerTextDrawTextSize(playerid, BlackBarTOP[playerid], 298.500000, 640.000000);
	PlayerTextDrawSetOutline(playerid, BlackBarTOP[playerid], 1);
	PlayerTextDrawSetShadow(playerid, BlackBarTOP[playerid], 0);
	PlayerTextDrawAlignment(playerid, BlackBarTOP[playerid], 2);
	PlayerTextDrawColor(playerid, BlackBarTOP[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, BlackBarTOP[playerid], 255);
	PlayerTextDrawBoxColor(playerid, BlackBarTOP[playerid], 255);
	PlayerTextDrawUseBox(playerid, BlackBarTOP[playerid], 1);
	PlayerTextDrawSetProportional(playerid, BlackBarTOP[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, BlackBarTOP[playerid], 0);

	BlackBarBOT[playerid] = CreatePlayerTextDraw(playerid, 320.000000, 420.000000, "_");
	PlayerTextDrawFont(playerid, BlackBarBOT[playerid], 1);
	PlayerTextDrawLetterSize(playerid, BlackBarBOT[playerid], 0.600000, 2.950001);
	PlayerTextDrawTextSize(playerid, BlackBarBOT[playerid], 298.500000, 640.000000);
	PlayerTextDrawSetOutline(playerid, BlackBarBOT[playerid], 1);
	PlayerTextDrawSetShadow(playerid, BlackBarBOT[playerid], 0);
	PlayerTextDrawAlignment(playerid, BlackBarBOT[playerid], 2);
	PlayerTextDrawColor(playerid, BlackBarBOT[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, BlackBarBOT[playerid], 255);
	PlayerTextDrawBoxColor(playerid, BlackBarBOT[playerid], 255);
	PlayerTextDrawUseBox(playerid, BlackBarBOT[playerid], 1);
	PlayerTextDrawSetProportional(playerid, BlackBarBOT[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, BlackBarBOT[playerid], 0);

	LSNText[playerid] = CreatePlayerTextDraw(playerid, 275.000000, 8.000000, "Los Santos Network");
	PlayerTextDrawFont(playerid, LSNText[playerid], 1);
	PlayerTextDrawLetterSize(playerid, LSNText[playerid], 0.270832, 1.649999);
	PlayerTextDrawTextSize(playerid, LSNText[playerid], 417.000000, -13.000000);
	PlayerTextDrawSetOutline(playerid, LSNText[playerid], 1);
	PlayerTextDrawSetShadow(playerid, LSNText[playerid], 0);
	PlayerTextDrawAlignment(playerid, LSNText[playerid], 1);
	PlayerTextDrawColor(playerid, LSNText[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, LSNText[playerid], 255);
	PlayerTextDrawBoxColor(playerid, LSNText[playerid], 50);
	PlayerTextDrawUseBox(playerid, LSNText[playerid], 0);
	PlayerTextDrawSetProportional(playerid, LSNText[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, LSNText[playerid], 0);

	LiveICON[playerid] = CreatePlayerTextDraw(playerid, 11.000000, 423.000000, "HUD:radar_light");
	PlayerTextDrawFont(playerid, LiveICON[playerid], 4);
	PlayerTextDrawLetterSize(playerid, LiveICON[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, LiveICON[playerid], 23.500000, 24.500000);
	PlayerTextDrawSetOutline(playerid, LiveICON[playerid], 1);
	PlayerTextDrawSetShadow(playerid, LiveICON[playerid], 0);
	PlayerTextDrawAlignment(playerid, LiveICON[playerid], 1);
	PlayerTextDrawColor(playerid, LiveICON[playerid], -16776961);
	PlayerTextDrawBackgroundColor(playerid, LiveICON[playerid], 255);
	PlayerTextDrawBoxColor(playerid, LiveICON[playerid], 50);
	PlayerTextDrawUseBox(playerid, LiveICON[playerid], 1);
	PlayerTextDrawSetProportional(playerid, LiveICON[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, LiveICON[playerid], 0);

	LeaveStreamButton[playerid] = CreatePlayerTextDraw(playerid, 536.000000, 424.000000, "LEAVE STREAM");
	PlayerTextDrawFont(playerid, LeaveStreamButton[playerid], 1);
	PlayerTextDrawLetterSize(playerid, LeaveStreamButton[playerid], 0.337500, 2.099997);
	PlayerTextDrawTextSize(playerid, LeaveStreamButton[playerid], 646.000000, 22.000000);
	PlayerTextDrawSetOutline(playerid, LeaveStreamButton[playerid], 1);
	PlayerTextDrawSetShadow(playerid, LeaveStreamButton[playerid], 0);
	PlayerTextDrawAlignment(playerid, LeaveStreamButton[playerid], 1);
	PlayerTextDrawColor(playerid, LeaveStreamButton[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, LeaveStreamButton[playerid], 255);
	PlayerTextDrawBoxColor(playerid, LeaveStreamButton[playerid], 50);
	PlayerTextDrawUseBox(playerid, LeaveStreamButton[playerid], 0);
	PlayerTextDrawSetProportional(playerid, LeaveStreamButton[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, LeaveStreamButton[playerid], 1);

	LiveText[playerid] = CreatePlayerTextDraw(playerid, 52.000000, 422.000000, "LIVE");
	PlayerTextDrawFont(playerid, LiveText[playerid], 1);
	PlayerTextDrawLetterSize(playerid, LiveText[playerid], 0.574998, 2.500000);
	PlayerTextDrawTextSize(playerid, LiveText[playerid], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, LiveText[playerid], 1);
	PlayerTextDrawSetShadow(playerid, LiveText[playerid], 0);
	PlayerTextDrawAlignment(playerid, LiveText[playerid], 2);
	PlayerTextDrawColor(playerid, LiveText[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, LiveText[playerid], 255);
	PlayerTextDrawBoxColor(playerid, LiveText[playerid], 50);
	PlayerTextDrawUseBox(playerid, LiveText[playerid], 0);
	PlayerTextDrawSetProportional(playerid, LiveText[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, LiveText[playerid], 0);

	ViewersText[playerid] = CreatePlayerTextDraw(playerid, 585.000000, 10.000000, "VIEWERS:");
	PlayerTextDrawFont(playerid, ViewersText[playerid], 1);
	PlayerTextDrawLetterSize(playerid, ViewersText[playerid], 0.254164, 1.250000);
	PlayerTextDrawTextSize(playerid, ViewersText[playerid], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, ViewersText[playerid], 1);
	PlayerTextDrawSetShadow(playerid, ViewersText[playerid], 0);
	PlayerTextDrawAlignment(playerid, ViewersText[playerid], 2);
	PlayerTextDrawColor(playerid, ViewersText[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, ViewersText[playerid], 255);
	PlayerTextDrawBoxColor(playerid, ViewersText[playerid], 50);
	PlayerTextDrawUseBox(playerid, ViewersText[playerid], 0);
	PlayerTextDrawSetProportional(playerid, ViewersText[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, ViewersText[playerid], 0);

	TotalViewers[playerid] = CreatePlayerTextDraw(playerid, 606.000000, 10.000000, "10");
	PlayerTextDrawFont(playerid, TotalViewers[playerid], 1);
	PlayerTextDrawLetterSize(playerid, TotalViewers[playerid], 0.350000, 1.150000);
	PlayerTextDrawTextSize(playerid, TotalViewers[playerid], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, TotalViewers[playerid], 1);
	PlayerTextDrawSetShadow(playerid, TotalViewers[playerid], 0);
	PlayerTextDrawAlignment(playerid, TotalViewers[playerid], 1);
	PlayerTextDrawColor(playerid, TotalViewers[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, TotalViewers[playerid], 255);
	PlayerTextDrawBoxColor(playerid, TotalViewers[playerid], 50);
	PlayerTextDrawUseBox(playerid, TotalViewers[playerid], 0);
	PlayerTextDrawSetProportional(playerid, TotalViewers[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, TotalViewers[playerid], 0);

	return 1;
}

public OnPlayerDisconnect(playerid, reason)
{
	PlayerTextDrawDestroy(playerid, BlackBarTOP[playerid]);
	PlayerTextDrawDestroy(playerid, BlackBarBOT[playerid]);
	PlayerTextDrawDestroy(playerid, LSNText[playerid]);
	PlayerTextDrawDestroy(playerid, LiveICON[playerid]);
	PlayerTextDrawDestroy(playerid, LeaveStreamButton[playerid]);
	PlayerTextDrawDestroy(playerid, LiveText[playerid]);
	PlayerTextDrawDestroy(playerid, ViewersText[playerid]);
	PlayerTextDrawDestroy(playerid, TotalViewers[playerid]);
	return 1;
}

public OnPlayerCommandText(playerid, cmdtext[])
{
	if(!strcmp(cmdtext, "/tdtest", true))
	{
		PlayerTextDrawShow(playerid, BlackBarTOP[playerid]);
		PlayerTextDrawShow(playerid, BlackBarBOT[playerid]);
		PlayerTextDrawShow(playerid, LSNText[playerid]);
		PlayerTextDrawShow(playerid, LiveICON[playerid]);
		PlayerTextDrawShow(playerid, LeaveStreamButton[playerid]);
		PlayerTextDrawShow(playerid, LiveText[playerid]);
		PlayerTextDrawShow(playerid, ViewersText[playerid]);
		PlayerTextDrawShow(playerid, TotalViewers[playerid]);
		SelectTextDraw(playerid, 0xFF0000FF);
		return 1;
	}
	return 0;
}
