/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

#include <a_samp>

new PlayerText:TruckerTD[MAX_PLAYERS][4];

public OnFilterScriptInit()
{
	return 1;
}

public OnFilterScriptExit()
{
	return 1;
}

public OnPlayerConnect(playerid)
{
	TruckerTD[playerid][0] = CreatePlayerTextDraw(playerid, 556.000000, 120.000000, "_");
	PlayerTextDrawFont(playerid, TruckerTD[playerid][0], 1);
	PlayerTextDrawLetterSize(playerid, TruckerTD[playerid][0], 0.600000, 3.649989);
	PlayerTextDrawTextSize(playerid, TruckerTD[playerid][0], 298.500000, 114.000000);
	PlayerTextDrawSetOutline(playerid, TruckerTD[playerid][0], 1);
	PlayerTextDrawSetShadow(playerid, TruckerTD[playerid][0], 0);
	PlayerTextDrawAlignment(playerid, TruckerTD[playerid][0], 2);
	PlayerTextDrawColor(playerid, TruckerTD[playerid][0], -1);
	PlayerTextDrawBackgroundColor(playerid, TruckerTD[playerid][0], 255);
	PlayerTextDrawBoxColor(playerid, TruckerTD[playerid][0], 65405);
	PlayerTextDrawUseBox(playerid, TruckerTD[playerid][0], 1);
	PlayerTextDrawSetProportional(playerid, TruckerTD[playerid][0], 1);
	PlayerTextDrawSetSelectable(playerid, TruckerTD[playerid][0], 0);

	TruckerTD[playerid][1] = CreatePlayerTextDraw(playerid, 529.000000, 111.000000, "Storage");
	PlayerTextDrawFont(playerid, TruckerTD[playerid][1], 3);
	PlayerTextDrawLetterSize(playerid, TruckerTD[playerid][1], 0.350000, 1.500000);
	PlayerTextDrawTextSize(playerid, TruckerTD[playerid][1], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, TruckerTD[playerid][1], 1);
	PlayerTextDrawSetShadow(playerid, TruckerTD[playerid][1], 0);
	PlayerTextDrawAlignment(playerid, TruckerTD[playerid][1], 1);
	PlayerTextDrawColor(playerid, TruckerTD[playerid][1], -65281);
	PlayerTextDrawBackgroundColor(playerid, TruckerTD[playerid][1], 255);
	PlayerTextDrawBoxColor(playerid, TruckerTD[playerid][1], 50);
	PlayerTextDrawUseBox(playerid, TruckerTD[playerid][1], 0);
	PlayerTextDrawSetProportional(playerid, TruckerTD[playerid][1], 1);
	PlayerTextDrawSetSelectable(playerid, TruckerTD[playerid][1], 0);

	TruckerTD[playerid][2] = CreatePlayerTextDraw(playerid, 504.000000, 130.000000, " ");
	PlayerTextDrawFont(playerid, TruckerTD[playerid][2], 3);
	PlayerTextDrawLetterSize(playerid, TruckerTD[playerid][2], 0.391666, 1.400000);
	PlayerTextDrawTextSize(playerid, TruckerTD[playerid][2], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, TruckerTD[playerid][2], 1);
	PlayerTextDrawSetShadow(playerid, TruckerTD[playerid][2], 0);
	PlayerTextDrawAlignment(playerid, TruckerTD[playerid][2], 1);
	PlayerTextDrawColor(playerid, TruckerTD[playerid][2], 9109759);
	PlayerTextDrawBackgroundColor(playerid, TruckerTD[playerid][2], 255);
	PlayerTextDrawBoxColor(playerid, TruckerTD[playerid][2], 50);
	PlayerTextDrawUseBox(playerid, TruckerTD[playerid][2], 0);
	PlayerTextDrawSetProportional(playerid, TruckerTD[playerid][2], 1);
	PlayerTextDrawSetSelectable(playerid, TruckerTD[playerid][2], 0);

	TruckerTD[playerid][3] = CreatePlayerTextDraw(playerid, 534.000000, 131.000000, " ");
	PlayerTextDrawFont(playerid, TruckerTD[playerid][3], 3);
	PlayerTextDrawLetterSize(playerid, TruckerTD[playerid][3], 0.262499, 1.350000);
	PlayerTextDrawTextSize(playerid, TruckerTD[playerid][3], 640.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, TruckerTD[playerid][3], 1);
	PlayerTextDrawSetShadow(playerid, TruckerTD[playerid][3], 0);
	PlayerTextDrawAlignment(playerid, TruckerTD[playerid][3], 1);
	PlayerTextDrawColor(playerid, TruckerTD[playerid][3], -16776961);
	PlayerTextDrawBackgroundColor(playerid, TruckerTD[playerid][3], 255);
	PlayerTextDrawBoxColor(playerid, TruckerTD[playerid][3], -16777166);
	PlayerTextDrawUseBox(playerid, TruckerTD[playerid][3], 0);
	PlayerTextDrawSetProportional(playerid, TruckerTD[playerid][3], 1);
	PlayerTextDrawSetSelectable(playerid, TruckerTD[playerid][3], 0);

	return 1;
}

public OnPlayerDisconnect(playerid, reason)
{
	PlayerTextDrawDestroy(playerid, TruckerTD[playerid][0]);
	PlayerTextDrawDestroy(playerid, TruckerTD[playerid][1]);
	PlayerTextDrawDestroy(playerid, TruckerTD[playerid][2]);
	PlayerTextDrawDestroy(playerid, TruckerTD[playerid][3]);
	return 1;
}

public OnPlayerCommandText(playerid, cmdtext[])
{
	if(!strcmp(cmdtext, "/tdtest", true))
	{
		PlayerTextDrawShow(playerid, TruckerTD[playerid][0]);
		PlayerTextDrawShow(playerid, TruckerTD[playerid][1]);
		PlayerTextDrawShow(playerid, TruckerTD[playerid][2]);
		PlayerTextDrawShow(playerid, TruckerTD[playerid][3]);
		return 1;
	}
	return 0;
}
